spring:
  datasource:
    url: jdbc:mysql://10.2.196.23:3306/evan?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Qwe123!@#
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
    continue-on-error: true
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootDemoHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
logging:
  level:
    com.evan: debug
    com.evan.mapper: debug
mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.evan.POJO


#false时为单机模式，true时为zookeeper高可用模式
canal.client.instances.example.clusterEnabled: true
#canal.client.instances.example.host: 10.2.196.23
#zookeeper 地址
canal.client.instances.example.zookeeperAddress: 10.2.192.231:2181,10.2.192.232:2181,10.2.192.233:2181

canal.client.instances.example.port: 11111
canal.client.instances.example.batchSize: 1000
canal.client.instances.example.acquireInterval: 1000
canal.client.instances.example.retryCount: 20

spring.main.allow-bean-definition-overriding: true

access_log_dir: F:/hadoop/mysql/
to_upload_log_dir: F:/hadoop/mysql/toupload
bakup_log_dir: F:/hadoop/mysql/bakup/
